src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClassWithStudentId.cls
public with sharing class ClassWithStudentId
{
    /**
method that returns a map where key is class and value is set of studentid in it. 
*/
    public static Map<Class__c,Set<Student__c>> getClassesWithStudentId()
    {
        List<Class__c> myClasses = [SELECT id,(SELECt id FROM Students__r) FROM Class__c]; 
        Map<Class__c,Set<Student__c>> classMap = new Map<Class__c,Set<Student__c>>();
        for(Class__c myClass : myClasses)
        {
            List<Student__c> studentList = myClass.Students__r;
            Set<Student__c> studentsSet = new Set<Student__c>(myClass.Students__r);
            System.debug(studentsSet);
            classMap.put(myclass, studentsSet);
        }
        return classMap;
    }
    
}