src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RAJ</fullName>
                </value>
                <value>
                    <fullName>CBSE</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_Size__c</fullName>
        <label>Max Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestStudentsInClass.cls
@isTest
public class TestStudentsInClass {
    
    @isTest
    static void testGetStudentList(){
        // insert dummy class record
        Class__c c = new Class__c(Board__c = 'CBSE',Max_Size__c=40);
        insert c;
        
        // insert dummy student record
        Student__c s = new Student__c(Name='Poonam',Last_Name__c='Dasani',Class__c=c.id);
        insert s;
        
        List<Student__c> studentList = StudentsInClass.getStudentList(c.id);
        System.assertEquals(s.id, studentList.get(0).id );
        
        List<String> studentName = StudentsInClass.getStudentNames(c.id);
        System.assertEquals('Poonam Dasani', studentName.get(0) );
        
        
        delete c;
        
    }
}