src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Max_Size__c</fullName>
        <label>Max Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Students__c</fullName>
        <label>Number of Students</label>
        <summaryForeignKey>Student__c.Class__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Students.cls
public class Students extends fflib_SObjectDomain {
	public Students(List<Student__c> sObjectList)
    {
        super(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Students(sObjectList);
        }
    }
    
    public Override void onBeforeInsert()
    {
        checkMaxLimit();
    }
    
    private void checkMaxLimit(){
        Set<Id> classId = new Set<Id>();
        for(Student__c student: (List<Student__c>)Records)
        {
          classId.add(student.Class__c);
        }
        
        Map<Id, Class__c> classMap = new Map<Id, Class__c>(new ClassSelecter(true).selectById(classId));
        for(Student__c student: (List<Student__c>)Records)
        {
          if(classMap.containsKey(student.Class__c) && classMap.get(student.Class__c).Max_Size__c <= classMap.get(student.Class__c).Number_of_Students__c)
          {
            	student.addError('Max Size crossed');
          }
        }
    }
}