src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Classes.cls
public class Classes extends fflib_SObjectDomain {
    
    public Classes(List<Class__c> sObjectList)
    {
        super(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Classes(sObjectList);
        }
    }
    
    public Override void onBeforeDelete()
    {
     	checkFemaleStudents();
    }
    
   
    
    private void checkFemaleStudents(){
        Set<Id> femaleClassIdSet = new Set<Id>();
        Set<Id> classIdSet = new Set<Id>();
        for(Class__c classObject : (List<Class__c>)Records){
            classIdSet.add(classObject.Id);
        }
        
        for(Student__c student: (new StudentsSelecter(true).selectByClass(classIdSet)))
        {
            femaleClassIdSet.add(student.Class__c);
        }
        
        for(Class__c classObject : (List<Class__c>)Records)
        {
			if(femaleClassIdSet.contains(classObject.Id))
            {
                classObject.addError('Could not remove class as it contains Female Students');
            }
        }
    }
}