src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentsInClass.cls
public class StudentsInClass {
   
    public static List<Student__c> getStudentList(String classId){
        List<Student__c> students = [SELECT Name FROM Student__c WHERE Class__c =: classId];
        return students;
    }
    
    public static List<String> getStudentNames(String classId){
        List<Student__c> students = [SELECT Name, Last_Name__c FROM Student__c WHERE Class__c =: classId];
        List<String> names = new List<String>();
        for(Student__c student : students){
            names.add(student.Name + ' ' + student.Last_Name__c);
        }
        return names;
    }
   
}