src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RAJ</fullName>
                </value>
                <value>
                    <fullName>CBSE</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class_Teacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class Teacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Detailed_Description__c</fullName>
        <label>Detailed Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Size__c</fullName>
        <label>Max Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>My_Count__c</fullName>
        <label>My Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Students__c</fullName>
        <label>Number of Students</label>
        <summaryForeignKey>Student__c.Class__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClassSelector.cls
public class ClassSelecter extends fflib_SObjectSelector 
{
    List<String> selectFields = new List<String> {'Id', 'Number_of_Students__c', 'Max_Size__c ', 'My_Count__c', 'Class_Teacher__c', 'Board__c', 'Detailed_Description__c', 'Fee__c'};

    public ClassSelector()
    {
        super(false);
    }
    
    public ClassSelector(Boolean includeFieldSetFields)
    {
        super(includeFieldSetFields);
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() 
    {
        return new List<Schema.SObjectField> 
        {
            Class__c.ID
        };
    }
    
    public Schema.SObjectType getSObjectType() 
    {
        return Class__c.sObjectType;
    }
    
    public List<Class__c> selectClassDetails() 
    {
        String query = String.format(
            'SELECT {0} FROM {1} LIMIT 100', new List<String>{string.join(selectFields, ','), getSObjectName()});
        return (List<Class__c>) database.query(query);
    }
    
    public List<Class__c> selectById(Set<ID> idSet) 
    {
        String query = String.format(
            'SELECT {0} FROM {1} WHERE Id IN :idSet', new List<String>{string.join(selectFields, ','), getSObjectName()});
        return (List<Class__c>) database.query(query);
    }

}