src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentsSelector.cls
public class StudentsSelector extends fflib_SObjectSelector 
{
List<String> selectFields = new List<String> {'Id', 'Class__c '};

    public StudentsSelector()
	{
		super(false);
	}
	
	public StudentsSelector(Boolean includeFieldSetFields)
	{
		super(includeFieldSetFields);
	}
    
    public List<Schema.SObjectField> getSObjectFieldList() 
    {
        return new List<Schema.SObjectField> {
            Student__c.ID
        };
    }
    
    public Schema.SObjectType getSObjectType() 
    {
        return Student__c.sObjectType;
    }
    
    public Integer getFemaleStudentCount(Set<ID> idSet) 
    {
        String sex = 'Female';
        String query = String.format(
            'SELECT Count(Id) FROM {0} WHERE Class__c IN :idSet AND Sex__c = :sex', new List<String>{getSObjectName()});
        return (Integer) database.countQuery(query);
    }
    
}