src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ManagerController.cls
//Class to update Manager__c field. Manager__c field is a lookup of Account.
	
public class ManagerController {
    public void populateManager(Opportunity o)
    { 
              if(o.BillToContact__c != NULL)
                {
                   if(o.Manager__c == NULL)
                   {
                       try{
                           o.Manager__c= o.AccountId;
                          update o;
                       }
                       catch(Exception e){
                           system.debug('exception occured : '+ e.getMessage());
                       }
                   }
                }
        }
    }