src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Opportunities.cls
public class Opportunities extends fflib_SObjectDomain {
    
    public Opportunities(List<Opportunity> sObjectList)
    {
        super(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Opportunities(sObjectList);
        }
    }
    
    public Override void onBeforeUpdate(Map<Id, SObject> existingRecords)
    {
        Set<id> oppIdSet = new Set<Id>();
        for(Opportunity opp : (List<Opportunity>) Records){
            oppIdSet.add(opp.Id); 
        }
        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>(new OpportunitiesSelector(true).selectById(oppIdSet));
        for(Opportunity opp : (List<Opportunity>) Records){
        if(opp.BillToContact__c != NULL)
                {
                   if(opp.Manager__c == NULL)
                   {
                       opp.Manager__c= oppMap.get(opp.Id).BillToContact__r.AccountId;
                   }
                }
        }
        
    }

}