src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseOrder__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PurchaseOrders</relationshipLabel>
        <relationshipName>PurchaseOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseOrder</label>
    <nameField>
        <label>PurchaseOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseOrderLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder__c</fullName>
        <label>PurchaseOrder</label>
        <referenceTo>PurchaseOrder__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PurchaseOrderLineItem</label>
    <nameField>
        <label>PurchaseOrderLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PurchaseOrderServiceTest.cls
@isTest
private class PurchaseOrderServiceTest 
{
    
    @isTest
    static void addRemoveItems()
    {
        Product__c prod = setProduct();
        
        PurchaseOrderService.SelectProduct sp = PurchaseOrderService.addItems(1, prod);
        System.assertEquals(sp.price, prod.price__c);
        
        List<PurchaseOrderService.SelectProduct> spList = new List<PurchaseOrderService.SelectProduct>();
        spList.add(sp);
        spList = PurchaseOrderService.removeItem(spList, prod.id);
        System.assertEquals(0, spList.size());
        
        List<Product__c> pList = new List<Product__c>();
        pList.add(prod);
        pList = PurchaseOrderService.removeItem(pList, prod.id);
        System.assertEquals(0, pList.size());
        
        Product__c queryprod = PurchaseOrderService.getProduct(prod.id);
        System.assertEquals(queryprod.id, prod.id);
    }
    
    
    @isTest
    static void purchase()
    {
        Product__c prod = setProduct();
        
        PurchaseOrderService.SelectProduct sp = PurchaseOrderService.addItems(1, prod);
        System.assertEquals(sp.price, prod.price__c);
        
        List<PurchaseOrderService.SelectProduct> spList = new List<PurchaseOrderService.SelectProduct>();
        spList.add(sp);  
        
        Contact c = new Contact();
        c.LastName = 'test1';
        insert c;
        Date d = Date.today();
        PurchaseOrder__c purchaseOrder = new PurchaseOrder__c();
        purchaseOrder.Contact__c = c.Id;
        purchaseOrder.Purchase_Date__c = d;
        purchaseOrder.Total_Amount__c = 30;
        insert purchaseOrder;
        
        PurchaseOrderService.purchase(spList, purchaseOrder);
        
        List<PurchaseOrderLineItem__c> purchaseOrderLineItemList = new List<PurchaseOrderLineItem>();
        purchaseOrderLineItemList = [SELECT Product FROM PurchaseOrderLineItem__c];
        System.assertEquals(purchaseOrderLineItemList.get(0).purchaseOrder.Id,  purchaseOrder.Id);
    }
    
    private static Product__c setProduct()
    {
    		Product__c prod = new Product__c();
        prod.price__c = 123;
        insert prod;
    }
}