src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <label>Stock</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseOrder__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PurchaseOrders</relationshipLabel>
        <relationshipName>PurchaseOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseOrder</label>
    <nameField>
        <label>PurchaseOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseOrderLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder__c</fullName>
        <label>PurchaseOrder</label>
        <referenceTo>PurchaseOrder__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>total_price__c</fullName>
        <formula>Product__r.Price__c  *  Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>total price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseOrderLineItem</label>
    <nameField>
        <label>PurchaseOrderLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PurchaseOrderLineItemTest.cls
@isTest
private class PurchaseOrderLineItemTest {
    
    @isTest
    public static void TestInsertPurchaseList() {
        Contact c = new Contact();
        c.LastName = 'test1';
        insert c;
        Date d = Date.today();
        PurchaseOrder__c purchaseOrder = new PurchaseOrder__c();
        purchaseOrder.Contact__c = c.Id;
        purchaseOrder.Purchase_Date__c = d;
        purchaseOrder.Total_Amount__c = 30;
        insert purchaseOrder;
        Product__c prodct = new Product__c();
        prodct.Name = 'Test';
        prodct.Price__c = 20;
        prodct.Stock__c = 10;
        insert prodct;
        PurchaseOrderLineItem__c purOrderItem = new PurchaseOrderLineItem__c(Quantity__c = 60, PurchaseOrder__c = purchaseOrder.Id,Product__c = prodct.Id);
        PurchaseOrderLineItem__c purOrderItem1 = new PurchaseOrderLineItem__c(Quantity__c = 80, PurchaseOrder__c = purchaseOrder.Id,Product__c = prodct.Id);
        List<PurchaseOrderLineItem__c> purOrderList = new List<PurchaseOrderLineItem__c>();
        purOrderList.add(purOrderItem);
		purOrderList.add(purOrderItem1);
		PurchaseOrderLineItem.insertPurchaseList(purOrderList);
        
        List<PurchaseOrderLineItem__c> p = [SELECT id,Total_Price__c  FROM PurchaseOrderLineItem__c Where Id =: purOrderList.get(0).Id];
        system.AssertEquals(p.size(),1);
        system.AssertNotEquals(p[0].id, null);
        system.assertEquals(purOrderItem.Id, p[0].Id, 'Values Does not Match');
    }
}