src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <label>Stock</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseOrder__c.object
<CustomObject>
    <label>PurchaseOrder</label>
    <nameField>
        <label>PurchaseOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseOrderLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder__c</fullName>
        <label>PurchaseOrder</label>
        <referenceTo>PurchaseOrder__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PurchaseOrderLineItem</label>
    <nameField>
        <label>PurchaseOrderLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PurchaseOrderController.cls
public with sharing class PurchaseOrderController 
{
   
    public PurchaseOrderController(ApexPages.StandardController stdController) 
    {
        purchaseOrder = new PurchaseOrder__c();
        selectProductList = new List<PurchaseOrderService.SelectProduct>();
        addProductList = ([SELECT Name,Price__c,Stock__c FROM Product__c] );
        isRender = true;
    }
    
    public PurchaseOrder__c purchaseOrder{get; set;}
    public List<Product__c> addProductList;
    public List<PurchaseOrderService.SelectProduct> selectProductList;
    public String pid;
    public boolean isRender{set;get;}
    public boolean isViewProducts{set;get;}
    
    public PageReference cancel()
    {
        PageReference returnPage = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));  
        return returnPage;
    }
    
    public void addItem()
    {
        pid=ApexPages.currentPage().getParameters().get('selectproductId');
        Product__c p = PurchaseOrderService.getProduct(pid);
        Decimal quantity = Decimal.valueOf(ApexPages.currentPage().getParameters().get(p.Name));

        selectproductlist.add(PurchaseOrderService.addItems(quantity, p));
        addProductList = PurchaseOrderService.removeItem(addProductList, pid);                                         
    }
    
    public void removeItem()
    { 
        pid=ApexPages.currentPage().getParameters().get('selectedproductId');
        PurchaseOrderLineItem__c pi=new PurchaseOrderLineItem__c();
        Product__c p=(PurchaseOrderService.getProduct(pid)); 
        addproductlist.add(p);
        selectProductList = PurchaseOrderService.removeItem(selectProductList, pid);
    }
    
    Public List<Product__c>  getaddproductlist()
    {
        Return addproductlist; 
    }
    
    Public List<PurchaseOrderService.SelectProduct>  getselectproductlist()
    {
        Return selectproductlist; 
    }
    
    public String getpid()
    {
        return pid;
    } 
    
    public boolean getisRender()
    {
        return isRender;
    } 
    
    public boolean getisViewProducts()
    {
        return (addproductlist!=null);
    } 
    
    public PageReference purchase()
    {
        try
        {
        	PurchaseOrderService.purchase(selectProductList, purchaseOrder);
        }
        catch(System.DMLException e)
        {   
            Apexpages.addMessages(e);
            return null;
        }
        PageReference acctPage = new ApexPages.StandardController(purchaseOrder).view();
        acctPage.setRedirect(true);
        return acctPage;
    }
}