src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <label>Stock</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductSelector.cls
public class ProductSelector extends fflib_SObjectSelector 
{  
    List<String> selectFields = new List<String>{'Name','Price__c', 'Stock__c'};
        
    public List<Schema.SObjectField> getSObjectFieldList() 
    {
        return new List<Schema.SObjectField> 
        {
            Product__c.Id,
			Product__c.Name
         };
    }

    public ProductSelector()
	{
		super(false);
	}
	
	public ProductSelector(Boolean includeFieldSetFields)
	{
		super(includeFieldSetFields);
	}
    
    public Schema.SObjectType getSObjectType() 
    {
        return Product__c.sObjectType;
    }

    public List<Product__c> selectByProductId(Set<ID> idSet) 
    {
    	
    	List<Product__c> products = new List<Product__c>();
		if(idSet != null && idSet.size() > 0) {
        		String query = String.format(
            		'SELECT {0} FROM {1} WHERE Id IN :idSet', new List<String>{string.join(selectFields, ','), getSObjectName()});
        		return (List<Product__c>) database.query(query);
		}
		return products;
    }

}