src/objects/PurchaseOrder__c.object
<CustomObject>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseOrder</label>
    <nameField>
        <label>PurchaseOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PurchaseOrderTest.cls
@isTest
private class PurchaseOrderTest {
    @isTest
    public static void testInsertPurchaseList() {
        PurchaseOrder__c purOrder = new PurchaseOrder__c(Total_Amount__c = 60);
        String purchaseOrderId = PurchaseOrder.insertPurchaseOrder(purOrder);
        
        List<PurchaseOrder__c> p = [SELECT id FROM PurchaseOrder__c Where Id =: purchaseOrderId];
        system.AssertEquals(p.size(),1);
        system.AssertNotEquals(p[0].id, null);
        system.assertEquals(purOrder.Total_Amount__c, p[0].Total_Amount__c, 'Values Does not Match');
    }
}