src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>YEAR(Today()) - YEAR( DOB__c )</formula>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentNameController.cls
public with sharing class StudentNameController {

    public Student__c studentObj{get;set;}
    public Id studentId{get;set;}
    Map<Id,Student__c> studentMap = new Map<Id,Student__c>();
    
    public StudentNameController() {
        // query for fetching all the record of th Student Object
        studentMap = new Map<id,Student__c>([select Id,Name,Last_Name__c,DOB__c,Age__c,Email__c from Student__c]);
        
    }
   
    public List<SelectOption> getStudentsName(){
        // List of options in picked list
        List<SelectOption> optionList = new List<SelectOption>();
        // list of students id
        List<Id> studentsId = new List<Id>();
        // add all student id from map
        studentsId.addAll(studentMap.keySet());
        for( Id student : studentsId){
            // add options in the optionList
            optionList.add(new SelectOption(studentMap.get(student).id, studentMap.get(student).Name + ' ' + studentMap.get(student).Last_Name__c));
        }       
        return optionList ;
    }
    
    public PageReference setStudent() {
        studentObj = studentMap.get(studentId);
        return null;
    }
}